# System
FROM tensorflow/tensorflow 
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/San_Francisco
ENV PYTHONUNBUFFERED 1
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PIP_NO_CACHE_DIR 1
RUN apt-get update && apt-get install -y \
    vim libglew2.1 libgl1-mesa-glx libosmesa6 \
    wget unrar cmake g++ libgl1-mesa-dev \
    libx11-6 openjdk-8-jdk x11-xserver-utils xvfb \
    && apt-get clean
RUN pip3 install --upgrade pip

# set WORKDIR
WORKDIR /home/root/rl_ws

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

# replace mirror
RUN apt-get install -q -y --no-install-recommends wget \
&& wget http://archive.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20230311ubuntu0.22.04.1_all.deb \
&& dpkg -i ./ca-certificates_20230311ubuntu0.22.04.1_all.deb
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse\n" > /etc/apt/sources.list && \
  echo "deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse\n" >> /etc/apt/sources.list && \
  echo "deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse\n" >> /etc/apt/sources.list && \
  echo "deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse\n" >> /etc/apt/sources.list

# dependencies for gym
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
 libxcursor-dev \
 libxrandr-dev \
 libxinerama-dev \
 libxi-dev \
 mesa-common-dev \
 zip \
 unzip \
 make \
#  gcc-8 \
#  g++-8 \
#  vulkan-utils \
#  mesa-vulkan-drivers \
#  pigz \
 git \
 libegl1 \
 git-lfs \
 libsm6 \
 xauth \
 x11-apps

# change pip mirror
RUN python -m pip install --upgrade pip \
&& pip config set global.index-url https://pypi.org/simple

# pip install requirements
COPY requirement.txt .
RUN pip install -r requirement.txt

# # Force gcc 8 to avoid CUDA 10 build issues on newer base OS
# RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
# RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8

# WAR for eglReleaseThread shutdown crash in libEGL_mesa.so.0 (ensure it's never detected/loaded)
# Can't remove package libegl-mesa0 directly (because of libegl1 which we need)
RUN rm /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0 /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0.0.0 /usr/share/glvnd/egl_vendor.d/50_mesa.json

# COPY nvidia_icd.json /usr/share/vulkan/icd.d/nvidia_icd.json
# COPY 10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json


ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_VISIBLE_DEVICES=all NVIDIA_DRIVER_CAPABILITIES=all

